### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by KevinAlavik** [DebianArch64/DebProvision#1]
Doesnt seem to work on windows, tried both ver

**Comment by DebianArch64** [comment]
> Doesnt seem to work on windows, tried both ver
> 

I'll check it out today :D

**Comment by DebianArch64** [comment]
> i cant use it becuz of my apple id :/

It works fine for me on Windows might be that you need to install iTunes beforehand: https://secure-appldnld.apple.com/itunes12/001-97787-20210421-F0E5A3C2-A2C9-11EB-A40B-A128318AD179/iTunes64Setup.exe

![image](https://user-images.githubusercontent.com/63203414/165154711-a78becc4-96ca-4a22-af0e-809d7fd06751.png)

**Comment by Rg4r** [comment]
> > Doesnt seem to work on windows, tried both ver
> 
> I can now confirm the issue is caused by command prompt closing when the program finishes running. I can create a simple fix for it when I come back home
> 
> For now you can see the true error by running it in powershell
 hi i am a windows and when i run the amd exe. for windows it shows mothing it just empty 
![xcv](https://user-images.githubusercontent.com/104602056/165863761-058f2df3-78d5-4e02-b2c7-c582421226ce.png)

**Comment by Rg4r** [comment]
**_### 



_**

**Comment by DebianArch64** [comment]
This issue is now fixed in this new update "(4/28/22 CST) -> Fixed ScarletCloud connection issues that could arise, fixed windows command prompt closing instead of showing error, and added connection text to make things less confusing"

It should tell you the error instead of closing out. If you got error -36607 then use another appleID
