### ISSUE TITLE
Too Many Developer accounts (How do I fix it)

### ISSUE THREAD

**Issue by lilredscarface** [DebianArch64/DebProvision#155]
pls tell me how i dont wanna jailbreak my phone to get spotify cracked 
![ScarletCloud 6_2_2023 6_27_21 PM](https://github.com/DebianArch64/DebProvision/assets/104290113/fed14e05-3326-4695-9594-32f1ad4a586e)

**Comment by SpektacleFR** [comment]
You have too many iPhones registered to your developer account, as stated in the message.  [This stack overflow question](https://stackoverflow.com/questions/11374039/delete-a-device-from-my-developer-account-to-increase-the-count) has answers that show how to prune your devices, but in case you don't want to read that, here's a TL;DR:

## Before we begin, please read this important note:
> Note that once you Disable the device then all the provision profiles associated with it will become invalid. The device will be removed from your account only when your membership is renewed.

Because of this, device pruning is a once-a-year process.  Make sure to disable ALL devices you don't use, so you don't have to wait a year.

## How to prune devices
1. Go to Certificates, Identifiers & Profiles
2. Go to Devices list (All or specific device i.e. iPhone, iPad)
3. Click on device name. If the device list is too long then you can search using the search option present in the top right corner
4. Click on Disable button

**Comment by DebianArch64** [comment]
As spectacle stated this doesn't have to do with ScarletCloud - use another account

**Comment by DebianArch64** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/104290113/244317697-169b3500-c023-4c4f-b070-3f91b1ce0a68.jpg) It’s completely blank tho????

That message is from Apple not Scarlet - the webpage you visited is glitched it should show you some more information.

If you don't own a paid developer account that's probably why, but if you do own a paid developer account it's recommended to use that in the standard version of Scarlet if you don't want to use a computer for installs
