### ISSUE TITLE
Unable to sign you in to your Apple ID. Try again later. (-36607

### ISSUE THREAD

**Issue by Monkiey** [DebianArch64/DebProvision#2]
Does this mean I try again later?

**Comment by DebianArch64** [comment]
> Does this mean I try again later?

This is an issue caused by how anisette is fetched with ScarletCloud. Just like AltServer Linux and Sideloadly we use anisette servers and the abuse of them is the cause of this error on *some* accounts. As a temporary solution you can try making a new appleID or login to iTunes

Issue is mentioned in the release description and a fix is being worked on -> "Warning: Scarlet and ScarletCloud use an anisette server and the abuse of this can cause "Unable to sign you into your Apple ID. Try again later. (-36607)" depending on the Apple account which is why I'm creating a new method for anisette generation"

**Comment by anisdj** [comment]
> > Does this mean I try again later?
> 
> This is an issue caused by how anisette is fetched with ScarletCloud. Just like AltServer Linux and Sideloadly we use anisette servers and the abuse of them is the cause of this error on _some_ accounts. As a temporary solution you can try making a new appleID or login to iTunes
> 
> Issue is mentioned in the release description and a fix is being worked on -> "Warning: Scarlet and ScarletCloud use an anisette server and the abuse of this can cause "Unable to sign you into your Apple ID. Try again later. (-36607)" depending on the Apple account which is why I'm creating a new method for anisette generation"

Hello do you know when will you fix this problem? @DebianArch64

**Comment by DebianArch64** [comment]
> > > Does this mean I try again later?
> > 
> > This is an issue caused by how anisette is fetched with ScarletCloud. Just like AltServer Linux and Sideloadly we use anisette servers and the abuse of them is the cause of this error on _some_ accounts. As a temporary solution you can try making a new appleID or login to iTunes
> > 
> > Issue is mentioned in the release description and a fix is being worked on -> "Warning: Scarlet and ScarletCloud use an anisette server and the abuse of this can cause "Unable to sign you into your Apple ID. Try again later. (-36607)" depending on the Apple account which is why I'm creating a new method for anisette generation"
> 
> Hello do you know when will you fix this problem? @DebianArch64 

I'll eventually get to it - creating a new way of generating anisette that remains PCless I have a few ideas about, but I'm mainly waiting to fix the other bugs right now

**Comment by Monkiey** [comment]
Yeah it worked with a different account.
