### ISSUE TITLE
Error Message "Your development team has reached the maximum number of registered iPhone devices."

### ISSUE THREAD

**Issue by RyzenCD** [DebianArch64/DebProvision#288]
Trying to install Scarlet using the Windows GUI version, it continues to give me the error "Your development team has reached the maximum number of registered iPhone devices." despite me trying 2 different Apple accounts. Both accounts have never registered any device other than my iPhone 11 running iOS 18.1.1 (22B91)

**Comment by DebianArch64** [comment]
> Trying to install Scarlet using the Windows GUI version, it continues to give me the error "Your development team has reached the maximum number of registered iPhone devices." despite me trying 2 different Apple accounts. Both accounts have never registered any device other than my iPhone 11 running iOS 18.1.1 (22B91)

Sadly nothing I can do here, it's a message from Apple directly - computer methods use the xCode API so whatever Apple's xCode would say this would. Although it's possible to remove devices it doesn't affect the counter which is why computer methods don't offer that option.

https://forums.developer.apple.com/forums/thread/92337
