### ISSUE TITLE
failed to get anisette

### ISSUE THREAD

**Issue by mAmged** [DebianArch64/DebProvision#36]
I get this error when trying to install Scarlet. tried to reinstall Scarlet Cloud again but I'm getting the same error.
![image](https://user-images.githubusercontent.com/1144321/188978699-9dee232d-9b4e-44d5-b0a7-11dfb9e26273.png)

Also, it seems that the host server timed out.

![image](https://user-images.githubusercontent.com/1144321/188979558-a997e899-ca89-45d2-ab78-d8dfd50089b1.png)

**Comment by DebianArch64** [comment]
> I get this error when trying to install Scarlet. tried to reinstall Scarlet Cloud again but I'm getting the same error. ![image](https://user-images.githubusercontent.com/1144321/188978699-9dee232d-9b4e-44d5-b0a7-11dfb9e26273.png)
> 
> Also, it seems that the host server timed out.
> 
> ![image](https://user-images.githubusercontent.com/1144321/188979558-a997e899-ca89-45d2-ab78-d8dfd50089b1.png)

The instructions for ScarletCloud say to run ScarletCloud as sudo one time and enable the MailPlugin to fix anisette errors. I also just restarted the anisette server so it should be up again

It's better to use ScarletCloud on other platforms like Linux and Windows because they are the only platforms that can have stable and native anisette without *tricks*

**Comment by mAmged** [comment]
it's now working fine, thanks @DebianArch64

**Comment by kosuke14** [comment]
same error on linux (Xubuntu 22.04 arm64)
