### ISSUE TITLE
This App Cannot Be Installed Because Its Integrity Could Not Be Verified error when installing any app

### ISSUE THREAD

**Issue by lewiwiii** [DebianArch64/DebProvision#88]
this error shows up while trying to install any app from any sideloading service (sideloadly, altstore and obv scarlet)

**Comment by Zany-Zachary1** [comment]
From my experience this happens because the app's `manifest.json` file has the wrong iOS version attached.
Try to extract the app, find `manifest.json`, and change the iOS version entry to your phone's version.

**Comment by DebianArch64** [comment]
> this error shows up while trying to install any app from any sideloading service (sideloadly, altstore and obv scarlet)

I've seen this happen only with one other person it was very weird, but I believe I know the root cause

Apple knows an app is installed by it's mobileprovision it extracts from the app then stores it on the system.
When an app is uninstalled it's supposed to remove this mobileprovision, but if apple fails to do this that app is listed as installed forever

Is this the issue you are experiencing? A three app limit error with apps you already uninstalled ? If so contact me on Twitter @GetScarlet

**Comment by lewiwiii** [comment]
> 

how is the entry called?

**Comment by lewiwiii** [comment]
> From my experience this happens because the app's `manifest.json` file has the wrong iOS version attached. Try to extract the app, find `manifest.json`, and change the iOS version entry to your phone's version.
 
how is the entry called?

**Comment by Maicom12** [comment]
Iap

**Comment by DebianArch64** [comment]
Closed to due inactivity. Re-open if needed
