### ISSUE TITLE
needs ios cli executable

### ISSUE THREAD

**Issue by firashacker** [DebianArch64/DebProvision#98]
since you compiled it for this many operating system and architecture i hope you can compile it to run on jailbroken ios host(libimobiledevice,usbmuxd) installed,i tried the darwin-arm64 i thought it must work but it didn't i'm not sure its the executable or the XinA12 jailbreak, confirm this if its the problem, thanks for your efforts.

**Comment by DebianArch64** [comment]
> since you compiled it for this many operating system and architecture i hope you can compile it to run on jailbroken ios host(libimobiledevice,usbmuxd) installed,i tried the darwin-arm64 i thought it must work but it didn't i'm not sure its the executable or the XinA12 jailbreak, confirm this if its the problem, thanks for your efforts.

The same library "ScarletGSA" used for handling the login and installs with your account is used inside both ScarletCloud and Scarlet.

Because they share an identical codebase Scarlet already has an Entitled version using LSApplicationWorkspace entitlements for installs and anisette entitlements for anisette. If you install the IPA with Trollstore or as a system app it will function as it should without a computer 

This IPA is available on my website "iPA (Trollstore)" - eventually I'll add a proper jailbroken version, but I have no devices to test with

**Comment by firashacker** [comment]
can i help you getting it done? i can let you ssh into my iphone.
